language: node_js
node_js: "stable"

before_install:
  - stty cols 80

cache:
  directories:
    - node_modules
env:
  - SAUCE_BUILD=TRAVIS_BUILD_NUMBER

node_js:
  - node

script:
  - npm run test
  - npm run testcafe
  - npm run snapshot # Visual regression tests

    #addons:
    #  sauce_connect: true

notifications:
  email: false
  
